### ISSUE TITLE
What Blender-like GUI widget set used?

### ISSUE THREAD

**Issue by Symbian9** [afraidofdark/ToolKit#6]
Can you drop some details on how ToolKit got Blender-like GUI?

I know only few toolkits/widgets which are WIP. Are you reinvented own?

- https://github.com/julianeisel/bWidgets
- https://github.com/hellozee/blender-toolbox-qt

**Comment by afraidofdark** [comment]
Thank you for sharing with me these ui frameworks. I have checked them. I didn't want to go for huge 3th party ui frameworks for the spesific, lightweight - easy of port and use requirements of the ToolKit. To be honest, I did not know about these frameworks aswell. Its good to know them.

I have used Dear Imgui for my ui drawings which is in total 11k lines of pure c++ (?11) code.
Its a gpu based ui framework, that is, its rendering itself on the drawing window with opengl / directx / vulkan apis.
So it does not comes with any dependecy at all, and can be easly built into web. Also it is very easy to put together target
ui design with it. If needed, customizing or adding new widgets is pretty straight forward aswell. In total 11k lines of code, how hard can it be ? Even while developing ToolKit, I have inspired from its phlosophy to be lean and simple. Providing people the editor and required general 3d processing power which its less than 30k lines of code, and wastly portable ... How hard can it be to pick it up and start working on your project ?

Because of it being dependency free, small, easy to use - extend nature, and easy of portability to many platforms I have choosen to go for imgui.

I intentionally mimic Blender by picking same / similar colors schemas - layout, icons, shortcuts. Transfering a knowledge that learned in somewhere else sound tempting to me. Why learn something knew for the same purpose ?

However Dear imgui has some shortcomings too.
It would be nice to have css + html like responsive designing abilities and skinning.
You have very limited custimization and skinning options. If you want more, you've got to change the rendering of the imgui components. I once tought using Electron + Javascript + Html + Css for the UI drawing. But it was gonna make things un neededly complicated.

The worst for me, when the frame rate of the scene drops (Valid only for real time scene renderings) UI become less responsive to user events. Actually, this is my program design issue more than imgui. But be ware, since gpu is drawing the ui, when its bussy, you will have ui responsibility issues. (Due to your design problems)
